List<Map<String, dynamic>> words = [
  {
    'word': '	ٱللَّهِ	',
    'Ru': '	Аллах	',
    'tj': '	Аллоҳ	',
    'uz': '	-	',
    'ir': '	الله	',
    'type': 'noun',
    'occurrence': 2550,
    'percentage': 3.2,
    'exampleAr': 'أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
    'exampleRu': 'Прошу защиты у Всевышнего Аллаха от сатаны проклятого, побиваемого',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيمِ	',
    'combinations': 'وَاللهِ  فَالله  لِلهِ  آللهُ  فَلِلَّهِ',
    'counter': 1
  },
  {
    'word': '	شَيۡطَان	',
    'Ru': '	Сатана	',
    'tj': '	Шайтон	',
    'uz': '	-	',
    'ir': '	شیطان	',
    'type': 'noun',
    'occurrence': 88,
    'percentage': 3.3,
    'exampleAr': '	أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيمِ	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيمِ	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	هُوَ	',
    'Ru': '	он (м)	',
    'tj': '	Ӯ, вай (м)	',
    'uz': '	-	',
    'ir': '	او(مذکر)	',
    'type': 'noun',
    'occurrence': 481,
    'percentage': 3.9,
    'exampleAr': '	قُلۡ هُوَ ٱللَّهُ أَحَدٌ ١	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	قُلۡ هُوَ ٱللَّهُ أَحَدٌ ١	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	هُمۡ	',
    'Ru': '	Они (м)	',
    'tj': '	Онҳо (м)	',
    'uz': '	-	',
    'ir': '	آنها(جمع مذکر)	',
    'type': 'noun',
    'occurrence': 444,
    'percentage': 4.5,
    'exampleAr':
        '	أُوْلَٰٓئِكَ أَصۡحَٰبُ ٱلۡجَنَّةِۖ هُمۡ فِيهَا خَٰلِدُونَ ٨٢	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	أُوْلَٰٓئِكَ أَصۡحَٰبُ ٱلۡجَنَّةِۖ هُمۡ فِيهَا خَٰلِدُونَ ٨٢	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	أَنۡتَ	',
    'Ru': '	Ты	',
    'tj': '	Ту (м)	',
    'uz': '	-	',
    'ir': '	تو(مذکر)	',
    'type': 'noun',
    'occurrence': 81,
    'percentage': 4.6,
    'exampleAr':
        '	لَّآ إِلَـٰهَ إِلَّآ أَنتَ سُبْحَـٰنَكَ إِنِّى كُنتُ مِنَ ٱلظَّـٰلِمِينَ ٨٧	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	لَّآ إِلَـٰهَ إِلَّآ أَنتَ سُبْحَـٰنَكَ إِنِّى كُنتُ مِنَ ٱلظَّـٰلِمِينَ ٨٧	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	أَنَا	',
    'Ru': '	Я	',
    'tj': '	Ман	',
    'uz': '	-	',
    'ir': '	من	',
    'type': 'noun',
    'occurrence': 68,
    'percentage': 4.7,
    'exampleAr': '	وَلَآ أَنَا۠ عَابِدٌۭ مَّا عَبَدتُّمْ ٤	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	وَلَآ أَنَا۠ عَابِدٌۭ مَّا عَبَدتُّمْ ٤	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	أَنۡتُمۡ	',
    'Ru': '	Вы (м)	',
    'tj': '	Шумо (м)	',
    'uz': '	-	',
    'ir': '	شما(جمع مذکر)	',
    'type': 'noun',
    'occurrence': 135,
    'percentage': 4.9,
    'exampleAr': '	وَلَآ أَنتُمْ عَـٰبِدُونَ مَآ أَعْبُدُ ٥	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	وَلَآ أَنتُمْ عَـٰبِدُونَ مَآ أَعْبُدُ ٥	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	نَحۡنُ	',
    'Ru': '	Мы	',
    'tj': '	Мо	',
    'uz': '	-	',
    'ir': '	ما	',
    'type': 'noun',
    'occurrence': 86,
    'percentage': 5,
    'exampleAr':
        '	إِنَّا نَحْنُ نَزَّلْنَا ٱلذِّكْرَ وَإِنَّا لَهُۥ لَحَـٰفِظُونَ ٩	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	إِنَّا نَحْنُ نَزَّلْنَا ٱلذِّكْرَ وَإِنَّا لَهُۥ لَحَـٰفِظُونَ ٩	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	مَنۡ	',
    'Ru': '	От, кто	',
    'tj': '	Кӣ	',
    'uz': '	-	',
    'ir': '	چه کسی	',
    'type': 'noun',
    'occurrence': 831,
    'percentage': 6,
    'exampleAr': '	وَمَنْ أَظْلَمُ مِمَّن مَّنَعَ مَسَـٰجِدَ ٱللَّهِ ۱۱۴	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	وَمَنْ أَظْلَمُ مِمَّن مَّنَعَ مَسَـٰجِدَ ٱللَّهِ ۱۱۴	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	هَلۡ	',
    'Ru': '	Делать?	',
    'tj': '	Оё	',
    'uz': '	-	',
    'ir': '	آیا	',
    'type': 'noun',
    'occurrence': 93,
    'percentage': 6.2,
    'exampleAr':
        '	قُلۡ هَلۡ يَسۡتَوِي ٱلۡأَعۡمَىٰ وَٱلۡبَصِيرُۚ أَفَلَا تَتَفَكَّرُونَ ٥٠	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	قُلۡ هَلۡ يَسۡتَوِي ٱلۡأَعۡمَىٰ وَٱلۡبَصِيرُۚ أَفَلَا تَتَفَكَّرُونَ ٥٠	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	خَيۡر	',
    'Ru': '	хороший, благой	',
    'tj': '	Накӯ; беҳтарин	',
    'uz': '	-	',
    'ir': '	خوبی	',
    'type': 'noun',
    'occurrence': 176,
    'percentage': 6.4,
    'exampleAr': '	وَهُوَ خَيْرُ ٱلْحَـٰكِمِينَ ٨٧	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	وَهُوَ خَيْرُ ٱلْحَـٰكِمِينَ ٨٧	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اِسۡم	',
    'Ru': '	Имя	',
    'tj': '	Исм, ном	',
    'uz': '	-	',
    'ir': '	اسم	',
    'type': 'noun',
    'occurrence': 39,
    'percentage': 6.4,
    'exampleAr': '	بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	رَحۡمَٰن	',
    'Ru': '	Милость	',
    'tj': '	Бахшоянда	',
    'uz': '	-	',
    'ir': '	بخشنده	',
    'type': 'noun',
    'occurrence': 57,
    'percentage': 6.5,
    'exampleAr': '	بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	رَحِيم	',
    'Ru': '	Милосердный	',
    'tj': '	Меҳрубон	',
    'uz': '	-	',
    'ir': '	مهربان	',
    'type': 'noun',
    'occurrence': 116,
    'percentage': 6.6,
    'exampleAr': '	بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	كَرِيم	',
    'Ru': '	Великодушный, щедрый	',
    'tj': '	Саховатманд	',
    'uz': '	-	',
    'ir': '	سخاوتمند	',
    'type': 'noun',
    'occurrence': 27,
    'percentage': 6.7,
    'exampleAr':
        '	يَٰٓأَيُّهَا ٱلۡإِنسَٰنُ مَا غَرَّكَ بِرَبِّكَ ٱلۡكَرِيمِ ٦	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	يَٰٓأَيُّهَا ٱلۡإِنسَٰنُ مَا غَرَّكَ بِرَبِّكَ ٱلۡكَرِيمِ ٦	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	حَمۡد	',
    'Ru': '	Хвала	',
    'tj': '	Ҳамд, ситоиш	',
    'uz': '	-	',
    'ir': '	ستایش	',
    'type': 'noun',
    'occurrence': 149,
    'percentage': 6.7,
    'exampleAr': '	ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ ٢	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ ٢	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	لِلهِ	',
    'Ru': '	Ради Аллаха, Для Аллаха	',
    'tj': '	(Аз) Барои Аллоҳ	',
    'uz': '	-	',
    'ir': '	برای الله	',
    'type': 'noun',
    'occurrence': 149,
    'percentage': 6.9,
    'exampleAr': '	ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ ٢	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ ٢	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	عَالَمِينَ	',
    'Ru': '	Миры	',
    'tj': '	Оламиён	',
    'uz': '	-	',
    'ir': '	عالمیان/جهانیان	',
    'type': 'noun',
    'occurrence': 73,
    'percentage': 7,
    'exampleAr': '	ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ ٢	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ ٢	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	مُسۡلِم	',
    'Ru': '	Мусульманин	',
    'tj': '	Мусалмон	',
    'uz': '	-	',
    'ir': '	مسلمان	',
    'type': 'noun',
    'occurrence': 42,
    'percentage': 7.1,
    'exampleAr': '	وَلَا تَمُوتُنَّ إِلَّا وَأَنتُم مُّسۡلِمُونَ ١٠٢	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	وَلَا تَمُوتُنَّ إِلَّا وَأَنتُم مُّسۡلِمُونَ ١٠٢	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	مُؤۡمِن	',
    'Ru': '	Верующий	',
    'tj': '	Муъмин	',
    'uz': '	-	',
    'ir': '	مومن/با ایمان	',
    'type': 'noun',
    'occurrence': 230,
    'percentage': 7.4,
    'exampleAr':
        '	هُوَ ٱلَّذِي خَلَقَكُمۡ فَمِنكُمۡ كَافِرٞ وَمِنكُم مُّؤۡمِنٞ	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	هُوَ ٱلَّذِي خَلَقَكُمۡ فَمِنكُمۡ كَافِرٞ وَمِنكُم مُّؤۡمِنٞ	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	مُشۡرِك	',
    'Ru': '	Многобожник	',
    'tj': '	Мушрик	',
    'uz': '	-	',
    'ir': '	مشرک	',
    'type': 'noun',
    'occurrence': 49,
    'percentage': 7.4,
    'exampleAr': '	وَمَآ أَنَا۠ مِنَ ٱلۡمُشۡرِكِينَ ٧٩	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	وَمَآ أَنَا۠ مِنَ ٱلۡمُشۡرِكِينَ ٧٩	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	كَافِر	',
    'Ru': '	Неверующий	',
    'tj': '	Кофир	',
    'uz': '	-	',
    'ir': '	کافر	',
    'type': 'noun',
    'occurrence': 134,
    'percentage': 7.6,
    'exampleAr': '	قُلۡ يَٰٓأَيُّهَا ٱلۡكَٰفِرُونَ ١	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	قُلۡ يَٰٓأَيُّهَا ٱلۡكَٰفِرُونَ ١	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	صَالِح	',
    'Ru': '	Праведный	',
    'tj': '	Накӯкор	',
    'uz': '	-	',
    'ir': '	نیکوکار	',
    'type': 'noun',
    'occurrence': 136,
    'percentage': 7.8,
    'exampleAr':
        '	مَنۡ عَمِلَ صَٰلِحٗا فَلِنَفۡسِهِۦۖ  وَمَنۡ أَسَآءَ فَعَلَيۡهَا	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	مَنۡ عَمِلَ صَٰلِحٗا فَلِنَفۡسِهِۦۖ  وَمَنۡ أَسَآءَ فَعَلَيۡهَا	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	يَوۡم	',
    'Ru': '	День	',
    'tj': '	Рӯз	',
    'uz': '	-	',
    'ir': '	روز	',
    'type': 'noun',
    'occurrence': 405,
    'percentage': 8.3,
    'exampleAr': '	مَٰلِكِ يَوۡمِ ٱلدِّينِ ٤ 	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	مَٰلِكِ يَوۡمِ ٱلدِّينِ ٤ 	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	دِين	',
    'Ru': '	Религия; День Воскресения	',
    'tj': '	Дин, рӯзи қиёмат	',
    'uz': '	-	',
    'ir': '	دین	',
    'type': 'noun',
    'occurrence': 92,
    'percentage': 8.4,
    'exampleAr': '	مَٰلِكِ يَوۡمِ ٱلدِّينِ ٤	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	مَٰلِكِ يَوۡمِ ٱلدِّينِ ٤	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اِيَّاكَ	',
    'Ru': '	Только тебя	',
    'tj': '	Танҳо туро	',
    'uz': '	-	',
    'ir': '	تنها تو را	',
    'type': 'noun',
    'occurrence': 24,
    'percentage': 8.4,
    'exampleAr': '	إِيَّاكَ نَعۡبُدُ وَإِيَّاكَ نَسۡتَعِينُ ٥	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	إِيَّاكَ نَعۡبُدُ وَإِيَّاكَ نَسۡتَعِينُ ٥	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	رَبّ	',
    'Ru': '	Бог, Господь	',
    'tj': '	Парвардигор, худованд	',
    'uz': '	-	',
    'ir': '	خداوند/پادشاه/صاحب غلام	',
    'type': 'noun',
    'occurrence': 971,
    'percentage': 9.7,
    'exampleAr': '	ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ ٢	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ ٢	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	مَا	',
    'Ru': '	Что; Не	',
    'tj': '	Чӣ; Не	',
    'uz': '	-	',
    'ir': '	چی	',
    'type': 'noun',
    'occurrence': 2154,
    'percentage': 12.4,
    'exampleAr': '	مِن شَرِّ مَا خَلَقَ ٢	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	مِن شَرِّ مَا خَلَقَ ٢	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	صِرَاط	',
    'Ru': '	Путь	',
    'tj': '	Роҳ	',
    'uz': '	-	',
    'ir': '	راه	',
    'type': 'noun',
    'occurrence': 45,
    'percentage': 12.5,
    'exampleAr': '	ٱهۡدِنَا ٱلصِّرَٰطَ ٱلۡمُسۡتَقِيمَ ٦	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	ٱهۡدِنَا ٱلصِّرَٰطَ ٱلۡمُسۡتَقِيمَ ٦	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	مُسۡتَقۡيِم	',
    'Ru': '	Прямой	',
    'tj': '	Рост	',
    'uz': '	-	',
    'ir': '	مستقیم	',
    'type': 'noun',
    'occurrence': 37,
    'percentage': 12.5,
    'exampleAr': '	ٱهۡدِنَا ٱلصِّرَٰطَ ٱلۡمُسۡتَقِيمَ ٦	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	ٱهۡدِنَا ٱلصِّرَٰطَ ٱلۡمُسۡتَقِيمَ ٦	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اَلَّذِيۡنَ	',
    'Ru': '	Те, кто	',
    'tj': '	Касоне ки, ононе ки	',
    'uz': '	-	',
    'ir': '	کسانی که	',
    'type': 'noun',
    'occurrence': 1080,
    'percentage': 13.9,
    'exampleAr': '	ٱهۡدِنَا ٱلصِّرَٰطَ ٱلۡمُسۡتَقِيمَ ٦	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	ٱهۡدِنَا ٱلصِّرَٰطَ ٱلۡمُسۡتَقِيمَ ٦	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	غَيۡر	',
    'Ru': '	Кроме	',
    'tj': '	Ғайр	',
    'uz': '	-	',
    'ir': '	بجز	',
    'type': 'noun',
    'occurrence': 147,
    'percentage': 14.1,
    'exampleAr': '	غَيۡرِ ٱلۡمَغۡضُوبِ عَلَيۡهِمۡ وَلَا ٱلضَّآلِّينَ ٧	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	غَيۡرِ ٱلۡمَغۡضُوبِ عَلَيۡهِمۡ وَلَا ٱلضَّآلِّينَ ٧	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	لَا	',
    'Ru': '	Нет	',
    'tj': '	Не	',
    'uz': '	-	',
    'ir': '	نه	',
    'type': 'noun',
    'occurrence': 1687,
    'percentage': 16.3,
    'exampleAr': '	غَيۡرِ ٱلۡمَغۡضُوبِ عَلَيۡهِمۡ وَلَا ٱلضَّآلِّينَ ٧	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	غَيۡرِ ٱلۡمَغۡضُوبِ عَلَيۡهِمۡ وَلَا ٱلضَّآلِّينَ ٧	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	ضَالِّينَ	',
    'Ru': '	Заблудшие	',
    'tj': '	Гумроҳон, гумроҳшудагон	',
    'uz': '	-	',
    'ir': '	گمراهان	',
    'type': 'noun',
    'occurrence': 14,
    'percentage': 16.3,
    'exampleAr': '	غَيۡرِ ٱلۡمَغۡضُوبِ عَلَيۡهِمۡ وَلَا ٱلضَّآلِّينَ ٧	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	غَيۡرِ ٱلۡمَغۡضُوبِ عَلَيۡهِمۡ وَلَا ٱلضَّآلِّينَ ٧	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	هِىَ	',
    'Ru': '	Она	',
    'tj': '	Ӯ, вай (зане)	',
    'uz': '	-	',
    'ir': '	او(مونث)	',
    'type': 'noun',
    'occurrence': 64,
    'percentage': 16.4,
    'exampleAr': '	فَأَلۡقَىٰهَا فَإِذَا هِيَ حَيَّةٞ تَسۡعَىٰ ٢٠	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	فَأَلۡقَىٰهَا فَإِذَا هِيَ حَيَّةٞ تَسۡعَىٰ ٢٠	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	كِتَاب	',
    'Ru': '	Книга	',
    'tj': '	Китоб	',
    'uz': '	-	',
    'ir': '	کتاب	',
    'type': 'noun',
    'occurrence': 261,
    'percentage': 16.7,
    'exampleAr': '	وَهَٰذَا كِتَٰبٌ أَنزَلۡنَٰهُ مُبَارَكٞ فَٱتَّبِعُوهُ 	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	وَهَٰذَا كِتَٰبٌ أَنزَلۡنَٰهُ مُبَارَكٞ فَٱتَّبِعُوهُ 	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اَنۡزَلۡنَا	',
    'Ru': '	Ниспослал	',
    'tj': '	Фуруд овардем	',
    'uz': '	-	',
    'ir': '	نازل کردیم	',
    'type': 'noun',
    'occurrence': 55,
    'percentage': 16.8,
    'exampleAr': '	وَهَٰذَا كِتَٰبٌ أَنزَلۡنَٰهُ مُبَارَكٞ فَٱتَّبِعُوهُ 	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	وَهَٰذَا كِتَٰبٌ أَنزَلۡنَٰهُ مُبَارَكٞ فَٱتَّبِعُوهُ 	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	ا ٰيّة	',
    'Ru': '	Аят; Знамение; Довод	',
    'tj': '	Оят, нишона, далел	',
    'uz': '	-	',
    'ir': '	آیه/نشانه	',
    'type': 'noun',
    'occurrence': 382,
    'percentage': 17.2,
    'exampleAr':
        '	كِتَٰبٌ أَنزَلۡنَٰهُ إِلَيۡكَ مُبَٰرَكٞ لِّيَدَّبَّرُوٓاْ ءَايَٰتِهِۦ 	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	كِتَٰبٌ أَنزَلۡنَٰهُ إِلَيۡكَ مُبَٰرَكٞ لِّيَدَّبَّرُوٓاْ ءَايَٰتِهِۦ 	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اَرض	',
    'Ru': '	Земля	',
    'tj': '	Замин	',
    'uz': '	-	',
    'ir': '	زمین	',
    'type': 'noun',
    'occurrence': 461,
    'percentage': 17.8,
    'exampleAr': '	ٱللَّهُ نُورُ ٱلسَّمَٰوَٰتِ وَٱلۡأَرۡضِ	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	ٱللَّهُ نُورُ ٱلسَّمَٰوَٰتِ وَٱلۡأَرۡضِ	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	سَمَاء	',
    'Ru': '	Небо	',
    'tj': '	Осмон	',
    'uz': '	-	',
    'ir': '	آسمان	',
    'type': 'noun',
    'occurrence': 310,
    'percentage': 18.2,
    'exampleAr': '	ٱللَّهُ نُورُ ٱلسَّمَٰوَٰتِ وَٱلۡأَرۡضِ	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	ٱللَّهُ نُورُ ٱلسَّمَٰوَٰتِ وَٱلۡأَرۡضِ	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اُوْلُواْ	',
    'Ru': '	Владеющий; Обладающий	',
    'tj': '	Соҳиб, доро	',
    'uz': '	-	',
    'ir': '	صاحب/مالک	',
    'type': 'noun',
    'occurrence': 43,
    'percentage': 18.3,
    'exampleAr':
        '	كِتَٰبٌ أَنزَلۡنَٰهُ إِلَيۡكَ مُبَٰرَكٞ لِّيَدَّبَّرُوٓاْ ءَايَٰتِهِۦ وَلِيَتَذَكَّرَ أُوْلُواْ ٱلۡأَلۡبَٰبِ ٢٩	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	كِتَٰبٌ أَنزَلۡنَٰهُ إِلَيۡكَ مُبَٰرَكٞ لِّيَدَّبَّرُوٓاْ ءَايَٰتِهِۦ وَلِيَتَذَكَّرَ أُوْلُواْ ٱلۡأَلۡبَٰبِ ٢٩	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	لَوۡ	',
    'Ru': '	Если	',
    'tj': '	Агар	',
    'uz': '	-	',
    'ir': '	اگر	',
    'type': 'noun',
    'occurrence': 201,
    'percentage': 18.5,
    'exampleAr': '	وَلَوْ شَآءَ ٱللَّهُ لَجَعَلَهُمْ أُمَّةًۭ وَٰحِدَةًۭ	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	وَلَوْ شَآءَ ٱللَّهُ لَجَعَلَهُمْ أُمَّةًۭ وَٰحِدَةًۭ	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	لِ	',
    'Ru': '	К; Для	',
    'tj': '	Барои	',
    'uz': '	-	',
    'ir': '	برای	',
    'type': 'noun',
    'occurrence': 1361,
    'percentage': 20.3,
    'exampleAr': '	لِّلَّهِ مَا فِى ٱلسَّمَـٰوَٰتِ وَمَا فِى ٱلْأَرْضِ 	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	لِّلَّهِ مَا فِى ٱلسَّمَـٰوَٰتِ وَمَا فِى ٱلْأَرْضِ 	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	مِنۡ	',
    'Ru': '	От	',
    'tj': '	Аз	',
    'uz': '	-	',
    'ir': '	از	',
    'type': 'noun',
    'occurrence': 3215,
    'percentage': 24.4,
    'exampleAr': '	أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيمِ	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيمِ	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	عَنۡ	',
    'Ru': '	От	',
    'tj': '	Дар; Аз	',
    'uz': '	-	',
    'ir': '	در	',
    'type': 'noun',
    'occurrence': 416,
    'percentage': 24.9,
    'exampleAr':
        '	رَّضِىَ ٱللَّهُ عَنْهُمْ وَرَضُوا۟ عَنْهُ ۚ ذَٰلِكَ ٱلْفَوْزُ ٱلْعَظِيمُ ١١٩	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	رَّضِىَ ٱللَّهُ عَنْهُمْ وَرَضُوا۟ عَنْهُ ۚ ذَٰلِكَ ٱلْفَوْزُ ٱلْعَظِيمُ ١١٩	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	لَقَدۡ/ قَد	',
    'Ru': '	По истине	',
    'tj': '	Ба дурусти ки 	',
    'uz': '	-	',
    'ir':
        '	 حتماً و یقیناً/قبل از فعل استفاده می‌شوند.دلیلش این است که گوینده جمله قصد دارد بر انجام شدن آن کار در زمان گذشته تاکید کند 	',
    'type': 'noun',
    'occurrence': 406,
    'percentage': 25.4,
    'exampleAr':
        '	وَلَقَدْ يَسَّرْنَا ٱلْقُرْءَانَ لِلذِّكْرِ فَهَلْ مِن مُّدَّكِرٍۢ ١٧	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	وَلَقَدْ يَسَّرْنَا ٱلْقُرْءَانَ لِلذِّكْرِ فَهَلْ مِن مُّدَّكِرٍۢ ١٧	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	قُرۡان	',
    'Ru': '	Коран	',
    'tj': '	Қуръон	',
    'uz': '	-	',
    'ir': '	قران	',
    'type': 'noun',
    'occurrence': 70,
    'percentage': 25.5,
    'exampleAr':
        '	وَلَقَدْ يَسَّرْنَا ٱلْقُرْءَانَ لِلذِّكْرِ فَهَلْ مِن مُّدَّكِرٍۢ ١٧	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	وَلَقَدْ يَسَّرْنَا ٱلْقُرْءَانَ لِلذِّكْرِ فَهَلْ مِن مُّدَّكِرٍۢ ١٧	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اِنۡ	',
    'Ru': '	Если	',
    'tj': '	Агар	',
    'uz': '	-	',
    'ir': '	اگر	',
    'type': 'noun',
    'occurrence': 691,
    'percentage': 26.4,
    'exampleAr': '	سَتَجِدُنِىٓ إِن شَآءَ ٱللَّهُ مِنَ ٱلصَّـٰبِرِينَ ١٠٢	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	سَتَجِدُنِىٓ إِن شَآءَ ٱللَّهُ مِنَ ٱلصَّـٰبِرِينَ ١٠٢	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	شَاءَ	',
    'Ru': '	Хотеть	',
    'tj': '	Хост	',
    'uz': '	-	',
    'ir': '	می خواست	',
    'type': 'noun',
    'occurrence': 56,
    'percentage': 26.5,
    'exampleAr': '	سَتَجِدُنِىٓ إِن شَآءَ ٱللَّهُ مِنَ ٱلصَّـٰبِرِينَ ١٠٢	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	سَتَجِدُنِىٓ إِن شَآءَ ٱللَّهُ مِنَ ٱلصَّـٰبِرِينَ ١٠٢	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اِنَّ	',
    'Ru': '	поистине	',
    'tj': '	Ҳароина	',
    'uz': '	-	',
    'ir': '	در	',
    'type': 'noun',
    'occurrence': 1534,
    'percentage': 28.4,
    'exampleAr': '	وَٱصْبِرُوٓا۟ ۚ إِنَّ ٱللَّهَ مَعَ ٱلصَّـٰبِرِينَ ٤٦	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	وَٱصْبِرُوٓا۟ ۚ إِنَّ ٱللَّهَ مَعَ ٱلصَّـٰبِرِينَ ٤٦	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اِنَّمَا	',
    'Ru': '	Не иначе как; кроме как	',
    'tj': '	ҷуз ин нест, ки	',
    'uz': '	-	',
    'ir': '	اما	',
    'type': 'noun',
    'occurrence': 145,
    'percentage': 28.6,
    'exampleAr':
        '	قُلْ إِنَّمَآ أَنَا۠ بَشَرٌۭ مِّثْلُكُمْ يُوحَىٰٓ إِلَىَّ أَنَّمَآ إِلَـٰهُكُمْ إِلَـٰهٌۭ وَٰحِدٌۭ 	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	قُلْ إِنَّمَآ أَنَا۠ بَشَرٌۭ مِّثْلُكُمْ يُوحَىٰٓ إِلَىَّ أَنَّمَآ إِلَـٰهُكُمْ إِلَـٰهٌۭ وَٰحِدٌۭ 	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اَعۡمَال	',
    'Ru': '	Дела, деяния	',
    'tj': '	Кирдор, амалҳо	',
    'uz': '	-	',
    'ir': '	اعمال	',
    'type': 'noun',
    'occurrence': 41,
    'percentage': 28.7,
    'exampleAr':
        '	وَلَنَآ أَعْمَـٰلُنَا وَلَكُمْ أَعْمَـٰلُكُمْ وَنَحْنُ لَهُۥ مُخْلِصُونَ ١٣٩	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	وَلَنَآ أَعْمَـٰلُنَا وَلَكُمْ أَعْمَـٰلُكُمْ وَنَحْنُ لَهُۥ مُخْلِصُونَ ١٣٩	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	بِ	',
    'Ru': '	Для, 	',
    'tj': '	Бо	',
    'uz': '	-	',
    'ir': '	با	',
    'type': 'noun',
    'occurrence': 510,
    'percentage': 29.3,
    'exampleAr': '	أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيمِ	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيمِ	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	فِى	',
    'Ru': '	В	',
    'tj': '	Дар	',
    'uz': '	-	',
    'ir': '	در	',
    'type': 'noun',
    'occurrence': 1684,
    'percentage': 31.5,
    'exampleAr': '	ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ ٥	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ ٥	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	سَبِيۡل	',
    'Ru': '	Путь	',
    'tj': '	Роҳ, сабил	',
    'uz': '	-	',
    'ir': '	راه	',
    'type': 'noun',
    'occurrence': 176,
    'percentage': 31.7,
    'exampleAr':
        '	إِنَّا هَدَيْنَـٰهُ ٱلسَّبِيلَ إِمَّا شَاكِرًۭا وَإِمَّا كَفُورًا ٣	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr':
        '	إِنَّا هَدَيْنَـٰهُ ٱلسَّبِيلَ إِمَّا شَاكِرًۭا وَإِمَّا كَفُورًا ٣	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	عَلى	',
    'Ru': '	На	',
    'tj': '	Бар	',
    'uz': '	-	',
    'ir': '	بر	',
    'type': 'noun',
    'occurrence': 1423,
    'percentage': 33.6,
    'exampleAr': '	وَعَلَى ٱللَّهِ فَلْيَتَوَكَّلِ ٱلْمُؤْمِنُونَ ١١	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	وَعَلَى ٱللَّهِ فَلْيَتَوَكَّلِ ٱلْمُؤْمِنُونَ ١١	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اَلَّذِى	',
    'Ru': '	Тот кто (м)	',
    'tj': '	Оне ки (м)	',
    'uz': '	-	',
    'ir': '	کسی که	',
    'type': 'noun',
    'occurrence': 304,
    'percentage': 33.9,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اَيُّكُمۡ	',
    'Ru': '	Кто (который) из вас	',
    'tj': '	Кадоме аз шумо	',
    'uz': '	-	',
    'ir': '	کدام یک از شما	',
    'type': 'noun',
    'occurrence': 59,
    'percentage': 34,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اَحۡسَن	',
    'Ru': '	Лучше; лучший	',
    'tj': '	накӯтар, беҳтар	',
    'uz': '	-	',
    'ir': '	نیکوتر/بهتر	',
    'type': 'noun',
    'occurrence': 36,
    'percentage': 34,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	إِلَىٰ	',
    'Ru': '	К	',
    'tj': '	Ба сӯи	',
    'uz': '	-	',
    'ir': '	به سوی	',
    'type': 'noun',
    'occurrence': 736,
    'percentage': 35,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	مَعَ	',
    'Ru': '	С	',
    'tj': '	Ҳамроҳи	',
    'uz': '	-	',
    'ir': '	همراه	',
    'type': 'noun',
    'occurrence': 163,
    'percentage': 35.2,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	عِنۡد	',
    'Ru': '	Рядом; когда	',
    'tj': '	назди; ҳангоми	',
    'uz': '	-	',
    'ir': '	نزد/چه زمانی	',
    'type': 'noun',
    'occurrence': 197,
    'percentage': 35.4,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اِنۡسَان	',
    'Ru': '	Человек	',
    'tj': '	Инсон, одам	',
    'uz': '	-	',
    'ir': '	انسان	',
    'type': 'noun',
    'occurrence': 65,
    'percentage': 35.5,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اِلَّا	',
    'Ru': '	Кроме	',
    'tj': '	Магар	',
    'uz': '	-	',
    'ir': '	مگر اینکه	',
    'type': 'noun',
    'occurrence': 664,
    'percentage': 36.4,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	امَنُوۡا	',
    'Ru': '	Уверовали	',
    'tj': '	Имон оварданд	',
    'uz': '	-	',
    'ir': '	ایمان اوردند	',
    'type': 'noun',
    'occurrence': 258,
    'percentage': 36.7,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	حَقّ	',
    'Ru': '	Истина	',
    'tj': '	Ҳақ, рост	',
    'uz': '	-	',
    'ir': '	حق	',
    'type': 'noun',
    'occurrence': 247,
    'percentage': 37,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اَوۡ	',
    'Ru': '	Или	',
    'tj': '	Ё, ё ин ки	',
    'uz': '	-	',
    'ir': '	یا	',
    'type': 'noun',
    'occurrence': 280,
    'percentage': 37.4,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	هَذَا	',
    'Ru': '	Этот (м)	',
    'tj': '	Ин (м)	',
    'uz': '	-	',
    'ir': '	این(مذکر)	',
    'type': 'noun',
    'occurrence': 225,
    'percentage': 37.7,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	هَٰذِهِۦ	',
    'Ru': '	Этот (ж)	',
    'tj': '	Ин (зан)	',
    'uz': '	-	',
    'ir': '	این(مونث)	',
    'type': 'noun',
    'occurrence': 47,
    'percentage': 37.7,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	ذَٰلِكَ	',
    'Ru': '	Тот (м)	',
    'tj': '	Он (м)	',
    'uz': '	-	',
    'ir': '	آن(مذکر)	',
    'type': 'noun',
    'occurrence': 478,
    'percentage': 38.3,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	تِلۡكَ	',
    'Ru': '	Тот (ж)	',
    'tj': '	Он (з)	',
    'uz': '	-	',
    'ir': '	آن(مونث)	',
    'type': 'noun',
    'occurrence': 43,
    'percentage': 38.4,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	هؤُلَاءِ	',
    'Ru': '	Эти 	',
    'tj': '	Инҳо (м / з)	',
    'uz': '	-	',
    'ir': '	اینها	',
    'type': 'noun',
    'occurrence': 46,
    'percentage': 38.4,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اُوْلئِكَ	',
    'Ru': '	Те	',
    'tj': '	Онҳо (м. / з)	',
    'uz': '	-	',
    'ir': '	آن ها	',
    'type': 'noun',
    'occurrence': 204,
    'percentage': 38.7,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اِذۡ	',
    'Ru': '	Когда (в прошедшем времени)	',
    'tj': '	Вақте ки (замони гузашта)	',
    'uz': '	-	',
    'ir': '	وقتی (زمان گذشته)	',
    'type': 'noun',
    'occurrence': 239,
    'percentage': 39,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اِذَا	',
    'Ru': '	Когда (В настоящем или будущем времени)	',
    'tj': '	Ҳангоме ки (замони оянда)	',
    'uz': '	-	',
    'ir': '	وقتی (زمان حال یا آینده)	',
    'type': 'noun',
    'occurrence': 423,
    'percentage': 39.5,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	جَاءَ	',
    'Ru': '	Пришел	',
    'tj': '	Омад	',
    'uz': '	-	',
    'ir': '	آمد	',
    'type': 'noun',
    'occurrence': 171,
    'percentage': 39.8,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	نَاس	',
    'Ru': '	Люди	',
    'tj': '	Одамон	',
    'uz': '	-	',
    'ir': '	مردم	',
    'type': 'noun',
    'occurrence': 241,
    'percentage': 40.1,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	فَعَلَ	',
    'Ru': '	Сделал	',
    'tj': '	Анҷом дод	',
    'uz': '	-	',
    'ir': '	انجام داد	',
    'type': 'noun',
    'occurrence': 100,
    'percentage': 40.2,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	جَعَلَ	',
    'Ru': '	Превратил	',
    'tj': '	Гардонид	',
    'uz': '	-	',
    'ir': '	ساختن	',
    'type': 'noun',
    'occurrence': 344,
    'percentage': 40.6,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	فَتَحَ	',
    'Ru': '	Открыл	',
    'tj': '	Кушод	',
    'uz': '	-	',
    'ir': '	باز کردن	',
    'type': 'noun',
    'occurrence': 25,
    'percentage': 40.7,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	قُلۡ	',
    'Ru': '	Скажи	',
    'tj': '	Бигӯ	',
    'uz': '	-	',
    'ir': '	بگو	',
    'type': 'noun',
    'occurrence': 332,
    'percentage': 41.19,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اَحَد	',
    'Ru': '	Один; Единственный	',
    'tj': '	Ягона, якто	',
    'uz': '	-	',
    'ir': '	یکتا	',
    'type': 'noun',
    'occurrence': 74,
    'percentage': 41.2,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	لَمۡ	',
    'Ru': '	Нет (в прошедшем времени)	',
    'tj': '	Не (дар замони гузашта)	',
    'uz': '	-	',
    'ir': '	خیر (زمان گذشته)	',
    'type': 'noun',
    'occurrence': 384,
    'percentage': 41.6,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	لَنۡ	',
    'Ru': '	Нет (в будущем времени)	',
    'tj': '	Не (дар замони оянда)	',
    'uz': '	-	',
    'ir': '	خیر (زمان آینده)	',
    'type': 'noun',
    'occurrence': 106,
    'percentage': 41.8,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	نَصَرَ	',
    'Ru': '	Помог	',
    'tj': '	Ёрӣ кард, ёри дод	',
    'uz': '	-	',
    'ir': '	یاری	',
    'type': 'noun',
    'occurrence': 80,
    'percentage': 41.9,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	خَلَقَ	',
    'Ru': '	Создал	',
    'tj': '	Офарид	',
    'uz': '	-	',
    'ir': '	خلق کرد/آفرید	',
    'type': 'noun',
    'occurrence': 237,
    'percentage': 42.2,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	ذَكَرَ	',
    'Ru': '	Упомянул	',
    'tj': '	Ба ёд овард	',
    'uz': '	-	',
    'ir': '	یاد کرد	',
    'type': 'noun',
    'occurrence': 151,
    'percentage': 42.4,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	عَبَدَ	',
    'Ru': '	Поклонился	',
    'tj': '	Ибодат кард	',
    'uz': '	-	',
    'ir': '	بنده	',
    'type': 'noun',
    'occurrence': 142,
    'percentage': 42.5,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	شَىۡء	',
    'Ru': '	Что-то; Предмет	',
    'tj': '	Чизе	',
    'uz': '	-	',
    'ir': '	چیز	',
    'type': 'noun',
    'occurrence': 283,
    'percentage': 42.9,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	ضَرَبَ	',
    'Ru': '	Ударил	',
    'tj': '	Зад	',
    'uz': '	-	',
    'ir': '	زد	',
    'type': 'noun',
    'occurrence': 50,
    'percentage': 43,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	سَمِعَ	',
    'Ru': '	Услышал	',
    'tj': '	Шунид	',
    'uz': '	-	',
    'ir': '	شنید	',
    'type': 'noun',
    'occurrence': 98,
    'percentage': 43.1,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	عَلِمَ	',
    'Ru': '	Знал	',
    'tj': '	Донист	',
    'uz': '	-	',
    'ir': '	دانست	',
    'type': 'noun',
    'occurrence': 562,
    'percentage': 43.8,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	عَمِلَ	',
    'Ru': '	Сделал	',
    'tj': '	Амал кард	',
    'uz': '	-	',
    'ir': '	عمل کرد	',
    'type': 'noun',
    'occurrence': 318,
    'percentage': 44.2,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	حَدِيثَ	',
    'Ru': '	Слово; не счастный случай	',
    'tj': '	Ҳадис, Сухан	',
    'uz': '	-	',
    'ir': '	حدیث	',
    'type': 'noun',
    'occurrence': 23,
    'percentage': 44.2,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اِله	',
    'Ru': '	Божество	',
    'tj': '	Худо	',
    'uz': '	-	',
    'ir': '	خدا	',
    'type': 'noun',
    'occurrence': 145,
    'percentage': 44.4,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	صَدۡر	',
    'Ru': '	Сердце	',
    'tj': '	Қафаси сина / дил	',
    'uz': '	-	',
    'ir': '	قفسه سینه	',
    'type': 'noun',
    'occurrence': 44,
    'percentage': 44.5,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	مَلَك	',
    'Ru': '	Король, владелец	',
    'tj': '	Молик, подшоҳ	',
    'uz': '	-	',
    'ir': '	مالک/پادشاه	',
    'type': 'noun',
    'occurrence': 88,
    'percentage': 44.6,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	جِنَّة	',
    'Ru': '	Джинн	',
    'tj': '	Ҷин	',
    'uz': '	-	',
    'ir': '	جن	',
    'type': 'noun',
    'occurrence': 32,
    'percentage': 44.6,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	يَا	',
    'Ru': '	О!	',
    'tj': '	Эй	',
    'uz': '	-	',
    'ir': '	ای	',
    'type': 'noun',
    'occurrence': 361,
    'percentage': 45.1,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	قَوۡم	',
    'Ru': '	Люди; 	',
    'tj': '	Қавм	',
    'uz': '	-	',
    'ir': '	قوم/گروه	',
    'type': 'noun',
    'occurrence': 383,
    'percentage': 45.6,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اَيُّهَا	',
    'Ru': '	О!	',
    'tj': '	Эй	',
    'uz': '	-	',
    'ir': '	ای (مذکر) 	',
    'type': 'noun',
    'occurrence': 153,
    'percentage': 45.8,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اَنۡ	',
    'Ru': '		',
    'tj': '	Ин ки	',
    'uz': '	-	',
    'ir': '	که	',
    'type': 'noun',
    'occurrence': 571,
    'percentage': 46.5,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اَنَّ	',
    'Ru': '		',
    'tj': '	Ин ки	',
    'uz': '	-	',
    'ir': '	که - اينکه(حرف تأکيد)	',
    'type': 'noun',
    'occurrence': 359,
    'percentage': 47,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	مُحَمَّد	',
    'Ru': '	Мухаммад	',
    'tj': '	Муҳаммад	',
    'uz': '	-	',
    'ir': '	محمد	',
    'type': 'noun',
    'occurrence': 4,
    'percentage': 47,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	رَسُوۡل	',
    'Ru': '	Пророк	',
    'tj': '	Паёмбар	',
    'uz': '	-	',
    'ir': '	پیام رسان/پیام بر	',
    'type': 'noun',
    'occurrence': 332,
    'percentage': 47.5,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	صَلَاة	',
    'Ru': '	Молитва	',
    'tj': '	Намоз / дуо 	',
    'uz': '	-	',
    'ir': '	نماز	',
    'type': 'noun',
    'occurrence': 83,
    'percentage': 47.5,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	شَرِيك	',
    'Ru': '	Партнер, подобный	',
    'tj': '	Шарик, ҳамто	',
    'uz': '	-	',
    'ir': '	شریک	',
    'type': 'noun',
    'occurrence': 40,
    'percentage': 47.6,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	مَاذَا	',
    'Ru': '	Что	',
    'tj': '	Чӣ чиз	',
    'uz': '	-	',
    'ir': '	چی	',
    'type': 'noun',
    'occurrence': 27,
    'percentage': 47.6,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	سُبۡحَٰنَ	',
    'Ru': '	Свят, пречист	',
    'tj': '	Пок, бе айб, бе камбудӣ	',
    'uz': '	-	',
    'ir': '	منزه است او	',
    'type': 'noun',
    'occurrence': 41,
    'percentage': 47.6,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	عَظِيم	',
    'Ru': '	Большой; Великий	',
    'tj': '	Бузург	',
    'uz': '	-	',
    'ir': '	بزرگ	',
    'type': 'noun',
    'occurrence': 107,
    'percentage': 47.8,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	طَيِّبَات	',
    'Ru': '	Блага	',
    'tj': '	Покҳо, накӯиҳо	',
    'uz': '	-	',
    'ir': '	چیزهای خوب/خوبیها	',
    'type': 'noun',
    'occurrence': 46,
    'percentage': 47.8,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	سَلَام	',
    'Ru': '	Мир	',
    'tj': '	Сулҳ; солим	',
    'uz': '	-	',
    'ir': '	صلح	',
    'type': 'noun',
    'occurrence': 42,
    'percentage': 47.9,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	نَبِىّ	',
    'Ru': '	Посланник	',
    'tj': '	Паёмбар	',
    'uz': '	-	',
    'ir': '	پیامبر	',
    'type': 'noun',
    'occurrence': 75,
    'percentage': 48,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	رَحۡمَة	',
    'Ru': '	Милосердие	',
    'tj': '	раҳмат	',
    'uz': '	-	',
    'ir': '	رحمت	',
    'type': 'noun',
    'occurrence': 114,
    'percentage': 48,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	عَبۡد	',
    'Ru': '	Раб	',
    'tj': '	Банда, ғулом	',
    'uz': '	-	',
    'ir': '	برده	',
    'type': 'noun',
    'occurrence': 125,
    'percentage': 48.3,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	سَوۡفَ	',
    'Ru': '	Скоро	',
    'tj': '	Ба зудӣ	',
    'uz': '	-	',
    'ir': '	خواهد شد	',
    'type': 'noun',
    'occurrence': 42,
    'percentage': 48.4,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اِبۡرَاهِيۡم	',
    'Ru': '	Ибрахим (Авраам)	',
    'tj': '	Иброҳим	',
    'uz': '	-	',
    'ir': '	ابراهیم	',
    'type': 'noun',
    'occurrence': 69,
    'percentage': 48.4,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	نَفۡس	',
    'Ru': '	Душа	',
    'tj': '	Нафс	',
    'uz': '	-	',
    'ir': '	روح/نفس	',
    'type': 'noun',
    'occurrence': 293,
    'percentage': 48.8,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	كَثِيۡر	',
    'Ru': '	Много	',
    'tj': '	Зиед, бисер	',
    'uz': '	-	',
    'ir': '	زیاد	',
    'type': 'noun',
    'occurrence': 63,
    'percentage': 48.9,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	ذَنۡب	',
    'Ru': '	Грех	',
    'tj': '	Гуноҳ	',
    'uz': '	-	',
    'ir': '	گناه	',
    'type': 'noun',
    'occurrence': 39,
    'percentage': 48.9,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	غَفُوۡر	',
    'Ru': '	Прощающий	',
    'tj': '	Бахшоянда	',
    'uz': '	-	',
    'ir': '	بخشنده	',
    'type': 'noun',
    'occurrence': 91,
    'percentage': 49,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	دُنۡيَا	',
    'Ru': '	Мир, свет	',
    'tj': '	Дунё, олам	',
    'uz': '	-	',
    'ir': '	دنیا	',
    'type': 'noun',
    'occurrence': 115,
    'percentage': 49.2,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	اخِرَة	',
    'Ru': '	Конец, загробная жизнь	',
    'tj': '	Охират	',
    'uz': '	-	',
    'ir': '	آخرت	',
    'type': 'noun',
    'occurrence': 115,
    'percentage': 49.4,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	عَذَاب	',
    'Ru': '	Мучение	',
    'tj': '	Азоб 	',
    'uz': '	-	',
    'ir': '	عذاب	',
    'type': 'noun',
    'occurrence': 322,
    'percentage': 49.8,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  },
  {
    'word': '	نَار	',
    'Ru': '	Огонь; Ад	',
    'tj': '	Дӯзах; оташ	',
    'uz': '	-	',
    'ir': '	آتش/جهنم	',
    'type': 'noun',
    'occurrence': 145,
    'percentage': 50,
    'exampleAr': '	-	',
    'exampleRu': '	-	',
    'exampleTj': '	-	',
    'exampleUz': '	-	',
    'exampleIr': '	-	',
    'combinations': '	-	',
    'counter': 1
  }
];
